### ISSUE TITLE
Incorrect normalising of discounted rewards

### ISSUE THREAD

**Issue by tall-josh** [keon/policy-gradient#5]
Hey mate, 

Great work, but I think you normalization of the discounted rewards is wrong.
`pg.py_line 64: rewards = rewards / np.std(rewards - np.mean(rewards))`

should maybe be:

`rewards = (rewards - np.mean(rewards)) / np.std(rewards - np.mean(rewards))`

**Comment by csxeba** [comment]
even better would be

`reward = (reward - np.mean(rewards)) / (np.std(rewards) + 1e-7)`

since mean centering isn't affecting stdev and adding a small constant ensures numerical stability.

**Comment by ZefanW** [comment]
why normalize discounted rewards like this?
I think it may cause some of the decisions always discouraged whatever they are nice or bad decisions.
Consider a MDP with rewards approximately obeying Gaussian distribution with mean 1 and tiny std, say 0.01 .
Then discounted rewards in one episode is always decreasing, and after normalizing in the way you said, the second half of the episode is always discouraged, even though it may contain good decisions. 
Why does almost every REINFORCE model normalize like this? Is there any scientific reference?

**Comment by keon** [comment]
fixed in recent update. thanks!
